[FIX/WIP] ObjectLinkedToModelingObj id property to incorporate dict key when object is a value within an ExplainableObjectDict. Tests still need debugging. (bug appears after self.recomputed_values = self.recompute_attributes())
self.filtered_hourly_quantities[2].id
Out[3]: 'hourly_occurrences_per_usage_pattern[uuid-Youtube-usage-in-France]-in-uuid-upload'
self.filtered_hourly_quantities[2].id
Traceback (most recent call last):
  File "/Users/vincentvillet/Library/Caches/pypoetry/virtualenvs/efootprint-DvRIyG39-py3.12/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c8bf6461363a>", line 1, in <module>
    self.filtered_hourly_quantities[2].id
  File "/Users/vincentvillet/dev/open-source-green/e-footprint-boavizta/efootprint/abstract_modeling_classes/object_linked_to_modeling_obj.py", line 27, in id
    raise ValueError(
ValueError: 7 values from 2025-01-01 01:00:00+00:00 to 2025-01-01 07:00:00+00:00 in dimensionless:
    [4000, 5000, 8000, 12000, 2000, 2000, 3000] doesn’t have a modeling_obj_container, hence it makes no sense to look for its ancestors
len(self.filtered_hourly_quantities)
Out[5]: 18